
import java.awt.CardLayout;
import java.awt.LayoutManager;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Wagner Semboloni
 */
public class BioCellsNotesGUI extends javax.swing.JPanel {
    //variables
    String bioCell, subject;
    
    //declare array of object
    BioCellsNotes[] cellArrList;
    
    //declare counter
    int count;
    /**
     * Creates new form BioCellsNotes
     */
    public BioCellsNotesGUI() {
        initComponents();
        cellArrList = new BioCellsNotes[6];
        
        //initialise counter
        count = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        back2Btn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        displayBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        bioCellTf = new javax.swing.JTextField();
        subjectLbl = new javax.swing.JLabel();
        subjectTf = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        titleLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleLbl.setText("Blood Cell Notes");

        backBtn.setText("Back Notes");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        back2Btn.setText("Back Main Bio");
        back2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back2BtnActionPerformed(evt);
            }
        });

        homeBtn.setText("Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        displayBtn.setText("Display");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        delBtn.setText("Delete");
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        viewBtn.setText("View");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        subjectLbl.setText("Subject:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(backBtn)
                                .addGap(26, 26, 26)
                                .addComponent(back2Btn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(titleLbl))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bioCellTf, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(subjectLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(subjectTf, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(displayBtn)
                                        .addGap(32, 32, 32)
                                        .addComponent(delBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(addBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(saveBtn)
                                        .addGap(26, 26, 26)
                                        .addComponent(viewBtn)))))
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(homeBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(titleLbl)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjectLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subjectTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bioCellTf, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayBtn)
                    .addComponent(delBtn)
                    .addComponent(addBtn)
                    .addComponent(saveBtn)
                    .addComponent(viewBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(back2Btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(homeBtn)
                .addGap(8, 8, 8))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if(layout instanceof CardLayout){
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "NotesBio");
        }
    }//GEN-LAST:event_backBtnActionPerformed

    private void back2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back2BtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if(layout instanceof CardLayout){
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "Biology");
        }       
    }//GEN-LAST:event_back2BtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "Main");
        }
    }//GEN-LAST:event_homeBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        //loop through objects
        for (int i = 0; i < cellArrList.length; i = i+1){
            JOptionPane.showMessageDialog(null, " "+ cellArrList[i].getBioCell() + " " + cellArrList[i].getSubject());
        }
    }//GEN-LAST:event_displayBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        if(subjectTf.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Sorry you need to enter subject first");
        }
        else if(count ==0){
            JOptionPane.showMessageDialog(null, "Sorry you need to have something to delete");
        }
        else{
            subject = subjectTf.getText();
            bioCell = bioCellTf.getText();

            for (int i = 0; i < count; i = i+1){
                if(cellArrList[i].getSubject().equals(subject)){
                    cellArrList[i] = cellArrList[count-1];
                    count = count - 1;
                    JOptionPane.showMessageDialog (null, "Deleted from the array: "+subject+ "," +bioCell+"from the array. There are" +count+ "items in the array");
                    break;
                }
                if (i==count-1){
                    JOptionPane.showMessageDialog(null, "Sorry, the item you are looking for could not be found.");
                }
            }
        }

    }//GEN-LAST:event_delBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed

        //Declare object class
        BioCellsNotes c;
        //Create EarthsNote class
        c = new BioCellsNotes();

        // get text from textfield
        bioCell = bioCellTf.getText();
        subject = subjectTf.getText();

        //adding details
        c.setBioCell(bioCell);
        c.setSubject(subject);

        //adding object to array
        cellArrList[count] = c;
        //increment counter
        count++;
    }//GEN-LAST:event_addBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        bioCell = bioCellTf.getText();
        subject = subjectTf.getText();

        BioCellsNotes c = new BioCellsNotes();
        c.setBioCell(bioCell);
        c.setSubject(subject);

        File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;

        try{
            outFile = new File ("output.dat");
            fStream = new FileOutputStream(outFile);
            oStream = new ObjectOutputStream(fStream);

            oStream.writeObject(c);

            JOptionPane.showMessageDialog(null, "File written successfully");

            oStream.close();
        }
        catch(IOException f){
            System.out.println(f);
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;

        try{
            inFile = new File ("output.dat");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream);

            EarthsNote x;
            x = (EarthsNote)oStream.readObject();

            JOptionPane.showMessageDialog(null, "Subject: "+x.getSubject() + "Note: " +x.getEarthNoteTf());

            oStream.close();
        }
        catch(IOException f){
            System.out.println(f);
        }
        catch(ClassNotFoundException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_viewBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton back2Btn;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField bioCellTf;
    private javax.swing.JButton delBtn;
    private javax.swing.JButton displayBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel subjectLbl;
    private javax.swing.JTextField subjectTf;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
