
import java.awt.CardLayout;
import java.awt.LayoutManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Wagner Semboloni
 */
public class BioImageQuiz3 extends javax.swing.JPanel {

    /**
     * Creates new form BioImageQuiz3
     */
    public BioImageQuiz3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        answerGroup = new javax.swing.ButtonGroup();
        titleLbl = new javax.swing.JLabel();
        question3Lbl = new javax.swing.JLabel();
        A_answerRb = new javax.swing.JRadioButton();
        B_answerRb = new javax.swing.JRadioButton();
        C_answerRb = new javax.swing.JRadioButton();
        D_answerRb = new javax.swing.JRadioButton();
        ansLbl = new javax.swing.JLabel();
        ansTf = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();
        previousBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        panelLbl = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setLayout(null);

        titleLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleLbl.setText("Image Quiz ");
        add(titleLbl);
        titleLbl.setBounds(20, 10, 83, 40);

        question3Lbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        question3Lbl.setText("Question 3: Which muscles are represented on picture Bellow?");
        add(question3Lbl);
        question3Lbl.setBounds(20, 60, 360, 15);

        answerGroup.add(A_answerRb);
        A_answerRb.setText("A -  Gluteus, triceps, quadriceps, hamstrings   ");
        A_answerRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_answerRbActionPerformed(evt);
            }
        });
        add(A_answerRb);
        A_answerRb.setBounds(20, 350, 247, 23);

        answerGroup.add(B_answerRb);
        B_answerRb.setText("B -  Biceps, quadriceps, hamstrings");
        add(B_answerRb);
        B_answerRb.setBounds(20, 370, 230, 23);

        answerGroup.add(C_answerRb);
        C_answerRb.setText("C - Calf, quadriceps, hamstrings, Gluteus");
        add(C_answerRb);
        C_answerRb.setBounds(20, 390, 240, 23);

        answerGroup.add(D_answerRb);
        D_answerRb.setText("D - Gluteus, quadriceps, hamstrings");
        add(D_answerRb);
        D_answerRb.setBounds(20, 410, 210, 23);

        ansLbl.setText("Answer:");
        add(ansLbl);
        ansLbl.setBounds(20, 440, 40, 14);
        add(ansTf);
        ansTf.setBounds(70, 440, 40, 20);

        submitBtn.setText("Submit ");
        add(submitBtn);
        submitBtn.setBounds(130, 440, 73, 23);

        nextBtn.setText("Next");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });
        add(nextBtn);
        nextBtn.setBounds(340, 440, 55, 23);

        previousBtn.setText("previous");
        previousBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousBtnActionPerformed(evt);
            }
        });
        add(previousBtn);
        previousBtn.setBounds(257, 440, 73, 23);

        homeBtn.setText("Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        add(homeBtn);
        homeBtn.setBounds(333, 470, 60, 23);

        panelLbl.setIcon(new javax.swing.ImageIcon("C:\\Users\\Wagner Semboloni\\College\\NCI\\First Year\\2 Semester\\OOP\\Project OOP\\OOP Project\\src\\quadriceps.png")); // NOI18N
        add(panelLbl);
        panelLbl.setBounds(40, 80, 370, 260);
    }// </editor-fold>//GEN-END:initComponents

    private void A_answerRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_answerRbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A_answerRbActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if(layout instanceof CardLayout){
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "BioImageQuiz4");
        }
    }//GEN-LAST:event_nextBtnActionPerformed

    private void previousBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if(layout instanceof CardLayout){
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "BioImageQuiz2");
        }
    }//GEN-LAST:event_previousBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "Main");
        }        
    }//GEN-LAST:event_homeBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton A_answerRb;
    private javax.swing.JRadioButton B_answerRb;
    private javax.swing.JRadioButton C_answerRb;
    private javax.swing.JRadioButton D_answerRb;
    private javax.swing.JLabel ansLbl;
    private javax.swing.JTextField ansTf;
    private javax.swing.ButtonGroup answerGroup;
    private javax.swing.JButton homeBtn;
    private javax.swing.JButton nextBtn;
    private javax.swing.JLabel panelLbl;
    private javax.swing.JButton previousBtn;
    private javax.swing.JLabel question3Lbl;
    private javax.swing.JButton submitBtn;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
