/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author x14112621
 */
public class HumanBodyQuizQ4 extends javax.swing.JPanel {

    /**
     * Creates new form HumanBodyQuizQ4
     */
    public HumanBodyQuizQ4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectionE = new javax.swing.JRadioButton();
        bioPopQuiz = new javax.swing.JLabel();
        SelectionF = new javax.swing.JRadioButton();
        q4Btn = new javax.swing.JButton();
        previousBtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        sectionA = new javax.swing.JRadioButton();
        selectionB = new javax.swing.JRadioButton();
        selectionC = new javax.swing.JRadioButton();
        selectionD = new javax.swing.JRadioButton();

        selectionE.setText("jRadioButton5");

        bioPopQuiz.setFont(new java.awt.Font("Franklin Gothic Book", 1, 24)); // NOI18N
        bioPopQuiz.setText("Biology Pop Quiz ");

        SelectionF.setText("None of Them");

        q4Btn.setText("Question 4");

        previousBtn.setText("Previous");

        nextBtn.setText("Next");

        jLabel1.setText("jLabel1");

        sectionA.setText("jRadioButton1");

        selectionB.setText("jRadioButton2");

        selectionC.setText("jRadioButton3");

        selectionD.setText("jRadioButton4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bioPopQuiz)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(q4Btn)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(previousBtn)
                                .addGap(18, 18, 18)
                                .addComponent(nextBtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectionB)
                            .addComponent(sectionA)
                            .addComponent(selectionC)
                            .addComponent(selectionD)
                            .addComponent(selectionE)
                            .addComponent(SelectionF))))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bioPopQuiz)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q4Btn)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previousBtn)
                    .addComponent(nextBtn))
                .addGap(51, 51, 51)
                .addComponent(sectionA)
                .addGap(18, 18, 18)
                .addComponent(selectionB)
                .addGap(18, 18, 18)
                .addComponent(selectionC)
                .addGap(18, 18, 18)
                .addComponent(selectionD)
                .addGap(18, 18, 18)
                .addComponent(selectionE)
                .addGap(18, 18, 18)
                .addComponent(SelectionF)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton SelectionF;
    private javax.swing.JLabel bioPopQuiz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton nextBtn;
    private javax.swing.JButton previousBtn;
    private javax.swing.JButton q4Btn;
    private javax.swing.JRadioButton sectionA;
    private javax.swing.JRadioButton selectionB;
    private javax.swing.JRadioButton selectionC;
    private javax.swing.JRadioButton selectionD;
    private javax.swing.JRadioButton selectionE;
    // End of variables declaration//GEN-END:variables
}
