
import java.awt.CardLayout;
import java.awt.LayoutManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alexander
 */
public class ImageQuizGeo extends javax.swing.JPanel {

    /**
     * Creates new form ImageQuizGeo
     */
    public ImageQuizGeo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GQImage1 = new javax.swing.JLabel();
        Question = new javax.swing.JLabel();
        AnsField1 = new javax.swing.JTextField();
        AnsField3 = new javax.swing.JTextField();
        AnsField2 = new javax.swing.JTextField();
        AnsField4 = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();
        AnsQ1 = new javax.swing.JLabel();
        AnsQ3 = new javax.swing.JLabel();
        AnsQ2 = new javax.swing.JLabel();
        AnsQ4 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        Home = new javax.swing.JButton();

        GQImage1.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        GQImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Volcanoe.png"))); // NOI18N
        GQImage1.setText("Question1");

        Question.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        Question.setText("Label each numbered part of the volcano");

        AnsField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnsField2ActionPerformed(evt);
            }
        });

        Submit.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        Submit.setText("Submit");

        AnsQ1.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        AnsQ1.setText("A.1");

        AnsQ3.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        AnsQ3.setText("A.3");

        AnsQ2.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        AnsQ2.setText("A.2");

        AnsQ4.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        AnsQ4.setText("A.4");

        Back.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Home.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Question))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AnsQ1)
                            .addComponent(AnsQ2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AnsField1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(AnsField2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AnsQ3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AnsQ4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AnsField3, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(AnsField4))))
                .addGap(99, 99, 99))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Back)
                        .addGap(134, 134, 134)
                        .addComponent(Submit)
                        .addGap(131, 131, 131)
                        .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(GQImage1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(GQImage1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Question)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AnsQ1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AnsField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AnsField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AnsQ3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AnsField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AnsQ2))
                        .addGap(41, 41, 41)
                        .addComponent(Back)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AnsField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AnsQ4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Submit)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Home)
                                .addGap(20, 20, 20))))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AnsField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnsField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnsField2ActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
         LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "Main");
        }
    }//GEN-LAST:event_HomeActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
        CardLayout cl = (CardLayout)layout;
        cl.show(getParent(), "Quiz");
    }                                       
    
    }//GEN-LAST:event_BackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnsField1;
    private javax.swing.JTextField AnsField2;
    private javax.swing.JTextField AnsField3;
    private javax.swing.JTextField AnsField4;
    private javax.swing.JLabel AnsQ1;
    private javax.swing.JLabel AnsQ2;
    private javax.swing.JLabel AnsQ3;
    private javax.swing.JLabel AnsQ4;
    private javax.swing.JButton Back;
    private javax.swing.JLabel GQImage1;
    private javax.swing.JButton Home;
    private javax.swing.JLabel Question;
    private javax.swing.JButton Submit;
    // End of variables declaration//GEN-END:variables
}
