
import java.awt.CardLayout;
import java.awt.LayoutManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Paul1997
 */
public class MainPage extends javax.swing.JPanel {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeadLbl = new javax.swing.JLabel();
        physBtn = new javax.swing.JButton();
        MathsBtn = new javax.swing.JButton();
        GeoBtn = new javax.swing.JButton();
        BIoBtn = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        HeadLbl.setFont(new java.awt.Font("Cambria", 1, 40)); // NOI18N
        HeadLbl.setText("Main Page");

        physBtn.setBackground(new java.awt.Color(153, 255, 51));
        physBtn.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        physBtn.setText("Physics");
        physBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        physBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                physBtnActionPerformed(evt);
            }
        });

        MathsBtn.setBackground(new java.awt.Color(153, 255, 51));
        MathsBtn.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        MathsBtn.setText("Maths");
        MathsBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MathsBtn.setPreferredSize(new java.awt.Dimension(450, 500));
        MathsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MathsBtnActionPerformed(evt);
            }
        });

        GeoBtn.setBackground(new java.awt.Color(153, 255, 51));
        GeoBtn.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        GeoBtn.setText("Geography");
        GeoBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        GeoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeoBtnActionPerformed(evt);
            }
        });

        BIoBtn.setBackground(new java.awt.Color(153, 255, 51));
        BIoBtn.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        BIoBtn.setText("Biology");
        BIoBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BIoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BIoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BIoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(physBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(HeadLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MathsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GeoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(HeadLbl)
                .addGap(18, 18, 18)
                .addComponent(physBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MathsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GeoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BIoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void physBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_physBtnActionPerformed
        // TODO add your handling code here:
           LayoutManager layout = getParent().getLayout();
         if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "Physics");
    }                                       
    
    }//GEN-LAST:event_physBtnActionPerformed

    private void MathsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MathsBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if(layout instanceof CardLayout){
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "Topics");
        }
    }//GEN-LAST:event_MathsBtnActionPerformed

    private void BIoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BIoBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if(layout instanceof CardLayout){
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "Biology");
        }
    }//GEN-LAST:event_BIoBtnActionPerformed

    private void GeoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeoBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if(layout instanceof CardLayout){
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "Geography");
        }          
    }//GEN-LAST:event_GeoBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BIoBtn;
    private javax.swing.JButton GeoBtn;
    private javax.swing.JLabel HeadLbl;
    private javax.swing.JButton MathsBtn;
    private javax.swing.JButton physBtn;
    // End of variables declaration//GEN-END:variables
}
