
import java.awt.CardLayout;
import java.awt.LayoutManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Paul1997
 */
public class Maths_Quiz extends javax.swing.JPanel {

    /**
     * Creates new form Maths_Quiz
     */
    public Maths_Quiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QuizLbl = new javax.swing.JLabel();
        CheckBox1 = new javax.swing.JCheckBox();
        Question1Lbl = new javax.swing.JLabel();
        CheckBox2 = new javax.swing.JCheckBox();
        CheckBox3 = new javax.swing.JCheckBox();
        CheckBox4 = new javax.swing.JCheckBox();
        Home1Btn = new javax.swing.JButton();
        Back2Btn = new javax.swing.JButton();

        QuizLbl.setFont(new java.awt.Font("Cambria", 1, 40)); // NOI18N
        QuizLbl.setText("Quiz");

        CheckBox1.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        CheckBox1.setText("Answer 1");

        Question1Lbl.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        Question1Lbl.setText("Question:");

        CheckBox2.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        CheckBox2.setText("Answer 2");

        CheckBox3.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        CheckBox3.setText("Answer 3");

        CheckBox4.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        CheckBox4.setText("Answer 4");

        Home1Btn.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        Home1Btn.setText("Home");
        Home1Btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Home1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home1BtnActionPerformed(evt);
            }
        });

        Back2Btn.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        Back2Btn.setText("Back");
        Back2Btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Back2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back2BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Back2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Home1Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addComponent(QuizLbl))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Question1Lbl)
                                    .addComponent(CheckBox1)
                                    .addComponent(CheckBox2)
                                    .addComponent(CheckBox3)
                                    .addComponent(CheckBox4))))
                        .addGap(0, 166, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(QuizLbl)
                .addGap(71, 71, 71)
                .addComponent(Question1Lbl)
                .addGap(18, 18, 18)
                .addComponent(CheckBox1)
                .addGap(18, 18, 18)
                .addComponent(CheckBox2)
                .addGap(33, 33, 33)
                .addComponent(CheckBox3)
                .addGap(28, 28, 28)
                .addComponent(CheckBox4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Home1Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Home1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home1BtnActionPerformed
        // TODO add your handling code here:
             LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "Main");
        }
    }//GEN-LAST:event_Home1BtnActionPerformed

    private void Back2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back2BtnActionPerformed
        // TODO add your handling code here:
            LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "Topics");
        }
    }//GEN-LAST:event_Back2BtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back2Btn;
    private javax.swing.JCheckBox CheckBox1;
    private javax.swing.JCheckBox CheckBox2;
    private javax.swing.JCheckBox CheckBox3;
    private javax.swing.JCheckBox CheckBox4;
    private javax.swing.JButton Home1Btn;
    private javax.swing.JLabel Question1Lbl;
    private javax.swing.JLabel QuizLbl;
    // End of variables declaration//GEN-END:variables
}
