


import java.awt.CardLayout;
import java.awt.LayoutManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alexander
 */
public class NotesGeo extends javax.swing.JPanel {

    /**
     * Creates new form NotesGeo
     */
    public NotesGeo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackBtn = new javax.swing.JButton();
        TitleLbl = new javax.swing.JLabel();
        EarthcardBtn = new javax.swing.JButton();
        Rockcard = new javax.swing.JButton();
        Mapcard = new javax.swing.JButton();
        Volcanoescard = new javax.swing.JButton();
        Earthnote = new javax.swing.JButton();
        Rocksnote = new javax.swing.JButton();
        Mapsnote = new javax.swing.JButton();
        Volcanoesnote = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        FlashCards = new javax.swing.JLabel();
        UserNotes = new javax.swing.JLabel();
        LimitLbl = new javax.swing.JLabel();

        BackBtn.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        TitleLbl.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        TitleLbl.setText("Notes");

        EarthcardBtn.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        EarthcardBtn.setText("Earth Card");
        EarthcardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EarthcardBtnActionPerformed(evt);
            }
        });

        Rockcard.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        Rockcard.setText("Rocks Card");
        Rockcard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RockcardActionPerformed(evt);
            }
        });

        Mapcard.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        Mapcard.setText("Maps Card");
        Mapcard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MapcardActionPerformed(evt);
            }
        });

        Volcanoescard.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        Volcanoescard.setText("Volcanoes Card");
        Volcanoescard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolcanoescardActionPerformed(evt);
            }
        });

        Earthnote.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        Earthnote.setText("Earth Note");
        Earthnote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EarthnoteActionPerformed(evt);
            }
        });

        Rocksnote.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        Rocksnote.setText("Rock Note");
        Rocksnote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RocksnoteActionPerformed(evt);
            }
        });

        Mapsnote.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        Mapsnote.setText("Map Note");
        Mapsnote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MapsnoteActionPerformed(evt);
            }
        });

        Volcanoesnote.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        Volcanoesnote.setText("Volcanoe Note");
        Volcanoesnote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolcanoesnoteActionPerformed(evt);
            }
        });

        Home.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        FlashCards.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        FlashCards.setText("Flash Cards");

        UserNotes.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        UserNotes.setText("User notes");

        LimitLbl.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        LimitLbl.setText("Only 6 notes per user");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Mapsnote)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Volcanoesnote))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Earthnote)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Rocksnote))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Mapcard)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Volcanoescard))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(EarthcardBtn)
                                .addGap(107, 107, 107)
                                .addComponent(Rockcard))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(TitleLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserNotes)
                            .addComponent(FlashCards)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackBtn)
                        .addGap(22, 22, 22)
                        .addComponent(LimitLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Home)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleLbl)
                .addGap(15, 15, 15)
                .addComponent(FlashCards)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EarthcardBtn)
                    .addComponent(Rockcard))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mapcard)
                    .addComponent(Volcanoescard))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UserNotes)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Earthnote)
                    .addComponent(Rocksnote))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mapsnote)
                    .addComponent(Volcanoesnote))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LimitLbl)
                    .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Home))
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
         LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "Main");
        }
    }//GEN-LAST:event_HomeActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
        CardLayout cl = (CardLayout)layout;
        cl.show(getParent(), "Geography");
    }   
    }//GEN-LAST:event_BackBtnActionPerformed

    private void VolcanoescardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolcanoescardActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
        CardLayout cl = (CardLayout)layout;
        cl.show(getParent(), "Volcanoes Notes");
    }   
    }//GEN-LAST:event_VolcanoescardActionPerformed

    private void EarthcardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EarthcardBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
        CardLayout cl = (CardLayout)layout;
        cl.show(getParent(), "Earth Card");
    }  
    }//GEN-LAST:event_EarthcardBtnActionPerformed

    private void RockcardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RockcardActionPerformed
        // TODO add your handling code here:
            LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
        CardLayout cl = (CardLayout)layout;
        cl.show(getParent(), "Rock Card");
    }  
    }//GEN-LAST:event_RockcardActionPerformed

    private void MapcardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MapcardActionPerformed
        // TODO add your handling code here:    
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
        CardLayout cl = (CardLayout)layout;
        cl.show(getParent(), "Map Card");
    }  
    }//GEN-LAST:event_MapcardActionPerformed

    private void EarthnoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EarthnoteActionPerformed
        // TODO add your handling code here:
            LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
        CardLayout cl = (CardLayout)layout;
        cl.show(getParent(), "Earth Note");
    }  
    }//GEN-LAST:event_EarthnoteActionPerformed

    private void RocksnoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RocksnoteActionPerformed
        // TODO add your handling code here:
            LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
        CardLayout cl = (CardLayout)layout;
        cl.show(getParent(), "Rocks Note");
    }  
    }//GEN-LAST:event_RocksnoteActionPerformed

    private void MapsnoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MapsnoteActionPerformed
        // TODO add your handling code here:
            LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
        CardLayout cl = (CardLayout)layout;
        cl.show(getParent(), "Maps Note");
    }  
    }//GEN-LAST:event_MapsnoteActionPerformed

    private void VolcanoesnoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolcanoesnoteActionPerformed
        // TODO add your handling code here:
            LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
        CardLayout cl = (CardLayout)layout;
        cl.show(getParent(), "Volcanoes Note");
    }  
    }//GEN-LAST:event_VolcanoesnoteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton EarthcardBtn;
    private javax.swing.JButton Earthnote;
    private javax.swing.JLabel FlashCards;
    private javax.swing.JButton Home;
    private javax.swing.JLabel LimitLbl;
    private javax.swing.JButton Mapcard;
    private javax.swing.JButton Mapsnote;
    private javax.swing.JButton Rockcard;
    private javax.swing.JButton Rocksnote;
    private javax.swing.JLabel TitleLbl;
    private javax.swing.JLabel UserNotes;
    private javax.swing.JButton Volcanoescard;
    private javax.swing.JButton Volcanoesnote;
    // End of variables declaration//GEN-END:variables
}
